version: '3.8'
services:
  dnstwist-webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    ports:
      - "8001:8000"
    container_name: dnstwist-webapp
    environment:
      - PORT=8000
    restart: unless-stopped 